language: node_js
node_js:
  - "8.15.1"

cache:
  directories:
    - "node_modules"

branches:
  only:
    - dev

install:
  - npm install
  - npm run build
  
branch: master

script:
  - ./deploy.sh
